# Generated by Django 2.1.1 on 2020-11-05 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badmintonactivitydetails',
            name='join_weChat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报名人员'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='weChat',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='微信账号'),
        ),
    ]
