# Generated by Django 2.1.1 on 2020-11-05 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_user', '0002_auto_20201105_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badmintonactivitydetails',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='badmintonactivitydetails',
            name='is_alive',
        ),
        migrations.AddField(
            model_name='badmintonactivitydetails',
            name='activity_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_user.BadmintonActivity', verbose_name='活动编号'),
        ),
    ]
